# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protocol/node.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13protocol/node.proto\"\r\n\x0bPingRequest\"\x1c\n\x0cPingResponse\x12\x0c\n\x04time\x18\x01 \x01(\r\"\x12\n\x10GetHeightRequest\" \n\x0eHeightResponse\x12\x0e\n\x06height\x18\x01 \x01(\x04\"o\n\x0bTransaction\x12\x0e\n\x06sender\x18\x01 \x01(\x0c\x12\x10\n\x08receiver\x18\x02 \x01(\x0c\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x02\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\x0c\x12\r\n\x05nonce\x18\x05 \x01(\r\x12\x11\n\tsignature\x18\x06 \x01(\x0c\"\x8b\x01\n\x05\x42lock\x12\r\n\x05index\x18\x01 \x01(\x04\x12\x11\n\ttimestamp\x18\x02 \x01(\r\x12\x0c\n\x04hash\x18\x03 \x01(\x0c\x12\r\n\x05phash\x18\x04 \x01(\x0c\x12\x19\n\x03txs\x18\x05 \x03(\x0b\x32\x0c.Transaction\x12\r\n\x05miner\x18\x06 \x01(\x0c\x12\x0b\n\x03pow\x18\x07 \x01(\x04\x12\x0c\n\x04\x64iff\x18\x08 \x01(\r\"\x15\n\x13GetLastBlockRequest\"\'\n\x16GetBlockByIndexRequest\x12\r\n\x05index\x18\x01 \x01(\x04\x32\xc6\x01\n\x04Node\x12%\n\x04Ping\x12\x0c.PingRequest\x1a\r.PingResponse\"\x00\x12\x31\n\tGetHeight\x12\x11.GetHeightRequest\x1a\x0f.HeightResponse\"\x00\x12.\n\x0cGetLastBlock\x12\x14.GetLastBlockRequest\x1a\x06.Block\"\x00\x12\x34\n\x0fGetBlockByIndex\x12\x17.GetBlockByIndexRequest\x1a\x06.Block\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protocol.node_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PINGREQUEST']._serialized_start=23
  _globals['_PINGREQUEST']._serialized_end=36
  _globals['_PINGRESPONSE']._serialized_start=38
  _globals['_PINGRESPONSE']._serialized_end=66
  _globals['_GETHEIGHTREQUEST']._serialized_start=68
  _globals['_GETHEIGHTREQUEST']._serialized_end=86
  _globals['_HEIGHTRESPONSE']._serialized_start=88
  _globals['_HEIGHTRESPONSE']._serialized_end=120
  _globals['_TRANSACTION']._serialized_start=122
  _globals['_TRANSACTION']._serialized_end=233
  _globals['_BLOCK']._serialized_start=236
  _globals['_BLOCK']._serialized_end=375
  _globals['_GETLASTBLOCKREQUEST']._serialized_start=377
  _globals['_GETLASTBLOCKREQUEST']._serialized_end=398
  _globals['_GETBLOCKBYINDEXREQUEST']._serialized_start=400
  _globals['_GETBLOCKBYINDEXREQUEST']._serialized_end=439
  _globals['_NODE']._serialized_start=442
  _globals['_NODE']._serialized_end=640
# @@protoc_insertion_point(module_scope)
