# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protocol import node_pb2 as protocol_dot_node__pb2


class NodeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/Node/Ping',
                request_serializer=protocol_dot_node__pb2.PingRequest.SerializeToString,
                response_deserializer=protocol_dot_node__pb2.PingResponse.FromString,
                )
        self.GetHeight = channel.unary_unary(
                '/Node/GetHeight',
                request_serializer=protocol_dot_node__pb2.GetHeightRequest.SerializeToString,
                response_deserializer=protocol_dot_node__pb2.HeightResponse.FromString,
                )
        self.GetLastBlock = channel.unary_unary(
                '/Node/GetLastBlock',
                request_serializer=protocol_dot_node__pb2.GetLastBlockRequest.SerializeToString,
                response_deserializer=protocol_dot_node__pb2.Block.FromString,
                )
        self.GetBlockByIndex = channel.unary_unary(
                '/Node/GetBlockByIndex',
                request_serializer=protocol_dot_node__pb2.GetBlockByIndexRequest.SerializeToString,
                response_deserializer=protocol_dot_node__pb2.Block.FromString,
                )


class NodeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHeight(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLastBlock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBlockByIndex(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NodeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=protocol_dot_node__pb2.PingRequest.FromString,
                    response_serializer=protocol_dot_node__pb2.PingResponse.SerializeToString,
            ),
            'GetHeight': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHeight,
                    request_deserializer=protocol_dot_node__pb2.GetHeightRequest.FromString,
                    response_serializer=protocol_dot_node__pb2.HeightResponse.SerializeToString,
            ),
            'GetLastBlock': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLastBlock,
                    request_deserializer=protocol_dot_node__pb2.GetLastBlockRequest.FromString,
                    response_serializer=protocol_dot_node__pb2.Block.SerializeToString,
            ),
            'GetBlockByIndex': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBlockByIndex,
                    request_deserializer=protocol_dot_node__pb2.GetBlockByIndexRequest.FromString,
                    response_serializer=protocol_dot_node__pb2.Block.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Node', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Node(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Node/Ping',
            protocol_dot_node__pb2.PingRequest.SerializeToString,
            protocol_dot_node__pb2.PingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetHeight(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Node/GetHeight',
            protocol_dot_node__pb2.GetHeightRequest.SerializeToString,
            protocol_dot_node__pb2.HeightResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetLastBlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Node/GetLastBlock',
            protocol_dot_node__pb2.GetLastBlockRequest.SerializeToString,
            protocol_dot_node__pb2.Block.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetBlockByIndex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Node/GetBlockByIndex',
            protocol_dot_node__pb2.GetBlockByIndexRequest.SerializeToString,
            protocol_dot_node__pb2.Block.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
